import Head from 'next/head'
import { Inter } from 'next/font/google'
import { trpc } from '@/utils/trpc'
import { css } from '@emotion/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const hello = trpc.hello.useQuery({ text: 'Home Page...' })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <p css={css({ margin: 0 })}>{hello.data?.greeting}</p>
      </main>
    </>
  )
}
